# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('url', models.TextField()),
                ('text', models.TextField()),
                ('bullshitMeter', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
