# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='bullshitMeter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
